input_data_path: "data/heart_cleveland_upload.csv"
output_model_path: "artifacts/model.pkl"
metric_path: "artifacts/metrics.json"
use_mlflow: false
mlflow_uri: "http://172.22.0.2:5001"
splitting_params:
  val_size: 0.2
  random_state: 3
model_params:
  model_type: "XGBoost"
  random_state: 255
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"
